### ISSUE TITLE
Dev Spaces / Gitea integration

### ISSUE THREAD

**Issue by agiertli** [agiertli/rhte-camelk-lab-setup#1]
- [x] Find a reliable way how to automate installation of Dev Spaces operator, with Image Puller enabled. Preferably in 'tooling' namespace
- [x] Image puller should be configured appropriately
- [x] Package devfile in seed repository https://github.com/agiertli/rhte-camelk-user-repository with following criteria

  -  [x] jBang, camel, kamel, helm, artemis container
  -  [x] Devfile must contains "projects" section which points to the repository itself. Since we will have N user's repo, we need to find a way how to automate customizing the devfile per repo. Example projects section look like this: 
```
  - schemaVersion: 2.1.0
metadata:
  name: sample-java-devfile
projects:
 - name: user1-camelk-user-repository
   git:
     remotes:
       origin: 'https://rhte-camelk-gitea-tooling.apps.cluster-4th5q.4th5q.sandbox1219.opentlc.com/user1/camelk-user-repository'  
     checkoutFrom:
       revision: main
```
- [x] Pre-provision N Workspace instances - with the user's gitea repository cloned 
- [x] Bonus points if we can inject git credentials into each workspace instance
